### ISSUE TITLE
Missing Variables

### ISSUE THREAD

**Issue by EboQuabena** [bthrasher/daily_BCSD#1]
Thanks for making this script available. I have been trying to run this script on some dataset and I realize it is asking for the variables "dec" and "pad", which is nowhere in the script. Can I get help as to what those variables are? Thank you

**Comment by bthrasher** [comment]
I have a python script that generates the NCL call strings with directory names, etc., and then runs them. You will likely need something similar that is specific to your particular setup. Pad simply defines the window for the rolling average used to generate the daily climatology, and dec is simply an index for the incoming files. (A long time ago I used decadal files instead of annual files, which is why it's named dec.)
